### ISSUE TITLE
help

### ISSUE THREAD

**Issue by andrelmariano** [TheJoin95/messenger-bot-quick-start#1]
Now I would like to know how can I make the bot send 2 answers to 1 question, for example: you type the price and the bot responds: I understand, the price is $ 10 and immediately after this response he sends another one of the type: I can send you the link for payment ? and in that case if the answer to that question is yes, the bot sends a new response and if it does not it sends another one. how can I do this ?

**Comment by andrelmariano** [comment]
i think of something like this: 
please see print : http://prntscr.com/iucx49

**Comment by TheJoin95** [comment]
Hi, you can do like this: https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

Send a message with quick replies and then, in the webhook, handle the response ;)
